obstacle_range: 8
raytrace_range: 8
footprint: [[0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5], [0.5, -0.5]]
robot_base_frame: /base_footprint

update_frequency: 5.0
publish_frequency: 3.0
transform_tolerance: 10.0

resolution: 0.05

static_layer:
  map_topic: /map
  subscribe_to_updates: true
  # track_unknown_space: true
  unknown_cost_value: 253

#robot_radius = ir_of_robot

obstacle_layer:
  observation_sources: laser_scan_sensor
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 3.5
  raytrace_range: 4
  laser_scan_sensor: {
    sensor_frame: laser_birdcage_r2000,
    data_type: LaserScan,
    topic: laser_birdcage_r2000/scan_filtered,
    marking: true,
    clearing: true
  }

inflation_layer:
  cost_scaling_factor: 1 #2.58
  inflation_radius: 1.75

