global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 10.0
  public_frequency: 10.0
  static_map: false

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
