global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 2.0
  publish_frequency: 1.0
  map_type: costmap
  static_map: true # TODO: how to false this?
  rolling_window: false

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"} # Alternative: ObstacleLayer
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  - {name: proxemic_layer, type: "social_navigation_layers::ProxemicLayer"}
  - {name: passing_layer, type: "social_navigation_layers::PassingLayer"}

