global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"} # Alternative: ObstacleLayer
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # - {name: proxemic_layer, type: "social_navigation_layers::ProxemicLayer"}
  # - {name: passing_layer, type: "social_navigation_layers::PassingLayer"}

