TrajectoryPlannerROS:   # params info in http://wiki.ros.org/base_local_planner

  # Robot Configuration Parameters
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  acc_lim_theta: 2.2
  max_vel_x: 1.0
  min_vel_x: 0.025
  max_vel_y: 0.2
  min_vel_y: 0.025
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  holonomic_robot: true
  #  y_vels: [-0.3, -0.1, 0.1, 0.3]

  #	Goal Tolerance Parameters
  yaw_goal_tolerance: 0.15 #default: 0.05
  xy_goal_tolerance: 0.2 #default: 0.1
  
