update_min_d: 0.25
update_min_a: 0.2
#laser_z_hit: 0.9
#laser_sigam_hit: 0.1
#laser_likelyhood_max_dist: 4.0
#kld_err: 0.01
#kld_z: 0.99
#odom_alpha1: 0.005
#odom_alpha2: 0.005
#odom_alpha3: 0.005
#odom_alpha4: 0.005
