DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.5
  min_vel_y: -0.5
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.4


  acc_lim_th: 2.2
  acc_lim_x: 1
  acc_lim_y: 0 # anything but 0  induces shaking

  acc_lim_theta: 2.2

  holonomic_robot: true

  goal_distance_bias: 20.0 # 3.0
  path_distance_bias: 32.0 #5.0 weighting for how much the controller should stay close to the path it was given

  pdist_scale: 11.0
  gdist_scale: 0.5

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.3
  #latch_xy_goal_tolerance: false #??????

  #heading_scoring: true

  #We'll configure how long and with what granularity we'll forward simulate trajectories
  sim_time: 4.0
  #sim_granularity: 0.025
  #angular_sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  #controller_frequency: 10.0

  #Parameters for scoring trajectories
  #goal_distance_bias: 0.8
  #path_distance_bias: 1.0
  #gdist_scale: 0.8
  #pdist_scale: 1.0
  occdist_scale: 0.5 #0.02
  #heading_lookahead: 0.325
  #oscillationresetdist: 0.05
