obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5], [0.5, -0.5]]
robot_base_frame: /base_footprint

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 10.0

resolution: 0.05

static_layer:
  map_topic: /map
  subscribe_to_updates: true


#robot_radius = ir_of_robot

obstacle_layer:
  observation_sources: laser_scan_sensor

  laser_scan_sensor: {
    sensor_frame: laser_birdcage_r2000,
    data_type: LaserScan,
    topic: laser_birdcage_r2000/scan_filtered,
    marking: true,
    clearing: true
  }

inflation_layer:
  cost_scaling_factor: 0.1
  inflation_radius: 2

