# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#

# Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state
shutdown_costmaps: false

# The rate in Hz at which to run the control loop and send velocity commands to the base
controller_frequency: 35.0
# How long the controller will wait in seconds without receiving a valid control
# before space-clearing operations are performed
controller_patience: 15.0


# The rate in Hz at which to run the global planning loop
planner_frequency: 10.0
# How long the planner will wait in seconds in an attempt to find a valid plan
# before space-clearing operations are performed
planner_patience: 5.0

# How long in seconds to allow for oscillation before executing recovery behaviors
oscillation_timeout: 10.0
# How far in meters the robot must move to be considered not to be oscillating
oscillation_distance: 0.2

# How many times to allow for planning retries before executing recovery behaviors
max_planning_retries: 35

## Planners - TODO: How to define properly through config?
# local planner - default is trajectory rollout
# base_local_planner: "dwa_local_planner/DWAPlannerROS"
# base_global_planner: "global_planner/GlobalPlanner" #alternatives: navfn/NavfnROS, carrot_planner/CarrotPlanner

## recovery behaviors; avoid spinning, but needs fall-back replanning
# recovery_behavior_enabled: true
#
# recovery_behaviors:
#   - name: 'super_conservative_reset1'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'conservative_reset1'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'aggressive_reset1'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'clearing_rotation1'
#     type: 'rotate_recovery/RotateRecovery'
#   - name: 'super_conservative_reset2'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'conservative_reset2'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'aggressive_reset2'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'clearing_rotation2'
#     type: 'rotate_recovery/RotateRecovery'
#
# super_conservative_reset1:
#   reset_distance: 3.0
# conservative_reset1:
#   reset_distance: 1.5
# aggressive_reset1:
#   reset_distance: 0.0
# super_conservative_reset2:
#   reset_distance: 3.0
# conservative_reset2:
#   reset_distance: 1.5
# aggressive_reset2:
#   reset_distance: 0.0

